[package]
name = "CG-Assignment5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = { git = "https://github.com/gudmunduro/glow.git", branch = "main"}
sdl2 = "0.35.2"
nalgebra = "0.31.2"